repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: local
  hooks:
  - id: pycln
    name: pycln
    stages: [ commit ]
    types: [python]
    language: system
    entry: pycln
  - id: black
    name: black
    stages: [ commit ]
    types: [python]
    language: system
    entry: black
  - id: isort
    name: isort
    stages: [ commit ]
    types: [python]
    language: system
    entry: isort
