apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hollys.fullname" . }}
  labels:
    {{- include "hollys.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host.ui | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "hollys.fullname" . }}
                port:
                  name: ui
    - host: {{ .Values.ingress.host.api | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "hollys.fullname" . }}
                port:
                  name: api
