apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hollys.fullname" . }}
  labels:
    {{- include "hollys.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "hollys.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "hollys.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
